USE [FinalDB]
GO
INSERT INTO [dbo].Voyage(Titre,DescCourte,DescLongue,Prix,IdContinent,NbPlaceDisponible,photo) 
VALUES 
('SÉJOUR, MAROC','La Résidence Igoudar est un endroit idéal pour recréer une atmosphère familiale. Situé à 600 m de la plage, à 750 m du zoo, à 1 km du centre ville, ...','L hôtel dispose de :bar, salle de détente, solarium, piscine, coffre-fort (à la réception/payant), Wi-Fi (espaces communautaires) et réception 24/24. Les appartements sont équipés de : chauffage, salon, cuisinette, mini-frigidaire et salle de bain. Note : Veuillez prendre note, que quelques des services/agréments ne sont en partie pas disponible à cause de la situation météorologique /de la saison. Address: Boulevard du 20 Aout, 80000 Agadir, Morocco.','1000','1','15','\Content\PhotoVoyage\marrakech-maroc.jpg'),
('SÉJOUR SENEGAL','Le typique village de Santa Maria et son charmant port de pêche, son architecture colorée, le sourire de ses habitants, sa vie nocturne,...','Spécialiste des îles du Cap Vert depuis plus de 25 ans, Secrets du Monde vous invite à découvrir ce magnifique archipel aux mille et une saveurs, aux mille et une montagnes, aux mille et une criques; 10 îles perdues au milieu de l océan Atlantique dotée d une nature sauvage & contrastée qui ne vous laisse pas indifférent ! Il existe tellement de charmes sur chacune des îles: les vallées vertiginueuses & splendides de Santo Antao sans oublier la mythique route de la corde, la vue époustoufflante du Monte Verde & le soleil couchant sur la baie de la festive Mindelo à Sao Vicente, la très discrète São Nicolau offrant montagnes & dragonniers, les étendues de sable blanc & les salines de Sal, les dunes, les plages & le désert de Viana de Boavista, l inaccesible Maio offrant de merveilleuses plages à découvrir si vous avez du temps, l historique Santiago (c est par elle que le peuple capverdien est né) offrant une diversité de paysages du nord au sud, le volcan majestueux de Fogo et le village tellement authentique de São Felipe, la nature sauvage & montagnes escarpées de Brava.','600','1','5','\Content\PhotoVoyage\Cap_Vert-Senegal.JPG'),
('SÉJOUR TUNISIE','L hôtel Tropicana 3* (normes locales) se situe tout près de Monastir et à 12 km de Sousse, au cœur de la station balnéaire de Skanès, face à une plage de sable fin. L aéroport de Monastir se trouve à 3 km.','Monastir : Cette plaisante cité balnéaire doit son expansion récente au président Habib Bourguiba. Après l indépendance, le Combattant suprême voulut promouvoir sa bourgade natale au rang de ville moderne, en faisant raser une partie de la médina pour aménager des esplanades, des avenues rectilignes bordées d arbres, des galeries à arcades et une mosquée portant son nom. Le président favorisa le développement touristique de cette côte aux plages de sable fin en la dotant d un aéroport international et de nombreux hôtels. Même si ces opérations ont volé à la ville une partie de son âme, vous trouverez à Monastir une séduisante atmosphère de vacances permanentes. ','2000','1','20','\Content\PhotoVoyage\tunisie-monastir.jpg'),	
('SÉJOUR NEVADA','L hôtel Tropicana 3* (normes locales) se situe dans le vieux Vegas.',' Las Vegas, dans le désert de Mojave dans le Nevada, est une ville réputée pour sa vie nocturne animée, ses casinos ouverts 24 h/24 et autres divertissements. Le point central de la ville correspond à sa rue principale, The Strip, longue d un peu plus de 4 miles. Ce boulevard abrite des hôtels à thème et des créations élaborées comme les fontaines synchronisées avec la musique ainsi que des répliques de monuments connus : pyramide égyptienne, Grand Canal de Venise, et Tour Eiffel. ','700','2','5','\Content\PhotoVoyage\Nevada-Amerique_ml'),	
('SÉJOUR PROVINCES DES PRAIRIES','L hôtel Tropicana 3* se situe dans la province des prairies','Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l imprimerie depuis les années 1500, quand un peintre anonyme assembla ensemble des morceaux de texte pour réaliser un livre spécimen de polices de texte.','300','2','20','\Content\PhotoVoyage\Province_Des_Prairies-Canada.jpg'),	
('SÉJOUR CHIWAWA','L hôtel Tropicana 3* se situe tout près de CHIWAWA.','Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l imprimerie depuis les années 1500, quand un peintre anonyme assembla ensemble des morceaux de texte pour réaliser un livre spécimen de polices de texte. ','800','2','1','\Content\PhotoVoyage\Chiwawa-mexique.jpg'),	
('SÉJOUR PHUKET','L hôtel Tropicana 3* se situe tout près de PHUKET. ','Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l imprimerie depuis les années 1500, quand un peintre anonyme assembla ensemble des morceaux de texte pour réaliser un livre spécimen de polices de texte. ','1700','3','50','\Content\PhotoVoyage\Phuket-Thailande.jpg'),	
('SÉJOUR HOKKAIDO','L hôtel Tropicana 3* se situe tout près de HOKKAIDO.','Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l imprimerie depuis les années 1500, quand un peintre anonyme assembla ensemble des morceaux de texte pour réaliser un livre spécimen de polices de texte.','1100','3','12','\Content\PhotoVoyage\Hokkaido-Japon.jpg'),	
('SÉJOUR BENGALE OCCIDENTAL','L hôtel Tropicana 3* se situe tout près du BENGALE OCCIDENTAL.','Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l imprimerie depuis les années 1500, quand un peintre anonyme assembla ensemble des morceaux de texte pour réaliser un livre spécimen de polices de texte. ','600','3','5','\Content\PhotoVoyage\Bengale-Inde.jpg'),	
('SÉJOUR, BRETAGNE','L hôtel Tropicana 3* se situe au coeur de Perros Guerrec.','Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l imprimerie depuis les années 1500, quand un peintre anonyme assembla ensemble des morceaux de texte pour réaliser un livre spécimen de polices de texte. ','300','4','7','\Content\PhotoVoyage\Perros-guirec-Bretagne.jpg'),	
('SÉJOUR SARDAIGNE','L hôtel Tropicana 3*  se situe tout près du centre de ville','Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l imprimerie depuis les années 1500, quand un peintre anonyme assembla ensemble des morceaux de texte pour réaliser un livre spécimen de polices de texte. ','1500','4','3','\Content\PhotoVoyage\Sardaigne-Italie.jpg'),	
('SÉJOUR GALICE','L hôtel Tropicana 3*  se situe en GALICE.','Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l imprimerie depuis les années 1500, quand un peintre anonyme assembla ensemble des morceaux de texte pour réaliser un livre spécimen de polices de texte.','700','4','7','\Content\PhotoVoyage\Galice-Espagne.jpg'),	
('SÉJOUR TAZMANIE','L hôtel Tropicana 3*  se situe au coeur de la TAZMANIE','Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l imprimerie depuis les années 1500, quand un peintre anonyme assembla ensemble des morceaux de texte pour réaliser un livre spécimen de polices de texte.','4500','5','6','\Content\PhotoVoyage\Tasmanie-Australie.jpg'),	
('SÉJOUR DIVISION OCCIDENTALE','L hôtel Tropicana 3*  se situe dans la division occidentale.','Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l imprimerie depuis les années 1500, quand un peintre anonyme assembla ensemble des morceaux de texte pour réaliser un livre spécimen de polices de texte.','3000','5','12','\Content\PhotoVoyage\nauru.jpg')
GO