//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THE_FINAL_PROJECT
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Commande
    {
        public long IdCommande { get; set; }
        [DisplayName("Place demandée")]
        public Nullable<int> NbPlaceDemande { get; set; }
        [DisplayName("Total de la commande")]
        public Nullable<double> TotalCommande { get; set; }
        [DisplayName("Solvabilité")]
        public Nullable<int> Solvabilite { get; set; }
        [DisplayName("État de la commande")]
        public Nullable<int> EtatCommande { get; set; }
        public long IdVoyage { get; set; }
        [DisplayName("Date de la commande")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> DateCommande { get; set; }
        public long IdClient { get; set; }
        
        public virtual Client Client { get; set; }
        public virtual Voyage Voyage { get; set; }
    }
}
