//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THE_FINAL_PROJECT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commande
    {
        public long IdCommande { get; set; }
        public Nullable<int> NbPlaceDemande { get; set; }
        public Nullable<double> TotalCommande { get; set; }
        public Nullable<int> Solvabilite { get; set; }
        public Nullable<int> EtatCommande { get; set; }
        public long IdVoyage { get; set; }
        public Nullable<System.DateTime> DateCommande { get; set; }
        public long IdClient { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Voyage Voyage { get; set; }
    }
}
