//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THE_FINAL_PROJECT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public long IdRegions { get; set; }
        public Nullable<long> IdPays { get; set; }
        public string Nom { get; set; }
    
        public virtual Pay Pay { get; set; }
    }
}
